apiVersion: v1
kind: Service
metadata:
  name: task-5-service
  namespace: task-5
spec:
  type: NodePort
  selector:
    app: task-5-app
  ports:
    - protocol: TCP
      port: 80          # Service port (external)
      targetPort: 80    # Pod/container port (should match the exposed port in Dockerfile)
      nodePort: 30480   # Fixed NodePort for external access

